export const healthPackages = [
  {
    id: 1,
    title: "Basic Fever Panel",
    numberOfTests: 7,
    tests: ["CBC", "ESR", "MP", "WIDAL", "URINE R/M"],
    parameters: 37,
    price: 1599,
    offerPrice: 799,
  },
  {
    id: 2,
    title: "Advanced Basic Fever Panel",
    numberOfTests: 7,
    tests: [
      "CBC + ESR",
      "MP",
      "Widal",
      "Urinal R/M",
      "TYPHIDOT",
      "DENGUE COMBO",
    ],
    parameters: 41,
    price: 3399,
    offerPrice: 1699,
  },
  {
    id: 3,
    title: "Women Health Panel",
    numberOfTests: 7,
    tests: ["CBC", "TFT", "LH", "FSH", "PROLACTIN", "URINE R/M"],
    parameters: 40,
    price: 2599,
    offerPrice: 1299,
  },
  {
    id: 4,
    title: "Basic Arthritis Panel",
    numberOfTests: 7,
    tests: ["CBC", "URIC ACID", "CALCIUM", "RA FACTOR", "CRP"],
    parameters: 18,
    price: 1799,
    offerPrice: 899,
  },
  {
    id: 5,
    title: "Advance Arthritis Panel",
    numberOfTests: 7,
    tests: [
      "CBC",
      "URIC ACID",
      "CALCIUM",
      "RA FACTOR",
      "CRP",
      "VITAMIN D3",
      "XRAY DOUBLE VIEW",
    ],
    parameters: 21,
    price: 3999,
    offerPrice: 1999,
  },
  {
    id: 6,
    title: "Diabetes Care Package",
    numberOfTests: 7,
    tests: ["FBS", "PPBS", "HBA1C"],
    parameters: 3,
    price: 799,
    offerPrice: 399,
  },
  {
    id: 7,
    title: "Basic Diabetes Care Package",
    numberOfTests: 7,
    tests: ["FBS", "PPBS", "HBA1C", "LIPID PROFILE", "CREATININE", "UREA"],
    parameters: 12,
    price: 1999,
    offerPrice: 999,
  },
  {
    id: 8,
    title: "Advanced Diabetes Care Package",
    numberOfTests: 7,
    tests: [
      "FBS",
      "PPBS",
      "HBA1C",
      "LIPID PROFILE",
      "CBC",
      "LFT",
      "KFT",
      "URINE R/M",
      "VITAMIN D3",
    ],
    parameters: 66,
    price: 5599,
    offerPrice: 2799,
  },
  {
    id: 9,
    title: "Complete Health Panel 1",
    numberOfTests: 36,
    tests: ["CBC", "LFT", "KFT", "Blood Sugar Random"],
    parameters: 36,
    price: 1599,
    offerPrice: 799,
  },
  {
    id: 10,
    title: "Complete Health Panel 2",
    numberOfTests: 56,
    tests: ["CBC", "LFT", "KFT", "Blood Sugar Random", "Urine R/M"],
    parameters: 56,
    price: 1999,
    offerPrice: 999,
  },

  {
    id: 11,
    title: "Complete Health Panel 3",
    numberOfTests: 66,
    tests: [
      "CBC",
      "LFT",
      "KFT",
      "Blood Sugar Random",
      "Urine R/M",
      "Lipid Profile",
      "TFT",
    ],
    parameters: 66,
    price: 2999,
    offerPrice: 1499,
  },
  {
    id: 12,
    title: "Complete Health Panel 4",
    numberOfTests: 69,
    tests: [
      "CBC",
      "LFT",
      "KFT",
      "Blood Sugar Random",
      "Urine R/M",
      "Lipid Profile",
      "TFT",
      "Vitamin D3",
      "Vitamin B12",
      "HB1AC",
    ],
    parameters: 69,
    price: 5999,
    offerPrice: 3000,
  },
  {
    id: 13,
    title: "Complete Health Panel 5",
    numberOfTests: 72,
    tests: [
      "CBC",
      "LFT",
      "KFT",
      "Blood Sugar Random",
      "Urine R/M",
      "Lipid Profile",
      "TFT",
      "Vitamin D3",
      "Vitamin B12",
      "HB1AC",
      "USG W/A",
      "CHEST XRAY",
      "ECG",
    ],
    parameters: 72,
    price: 8399,
    offerPrice: 4200,
  },
];
