export const conditions = [
  {
    name: "Pregnancy Checkup",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/Pregnancy Checkup",
  },
  {
    name: "Diabetes Test",
    icon: "/searchTestAndPackages/Diabetes.svg",
    link: "/search-test/Diabetes Test",
  },
  {
    name: "HIV Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/HIV Test",
  },
  {
    name: "Arthritis Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/Arthritis Test",
  },
  {
    name: "Kidney Function Test",
    icon: "/searchTestAndPackages/Disorders of Kidney.svg",
    link: "/search-test/Kidney Function Test",
  },
  {
    name: "Liver Function Test",
    icon: "/searchTestAndPackages/Disease of Liver.svg",
    link: "/search-test/Liver Function Test",
  },
  {
    name: "Stool Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/Stool Test",
  },
  {
    name: "Thyroid Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/Thyroid Test",
  },
  {
    name: "CBC Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/CBC Test",
  },
  {
    name: "Allergy Test",
    icon: "/searchTestAndPackages/Allergy.svg",
    link: "/search-test/Allergy Test",
  },
  {
    name: "Urine Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/Urine Test",
  },
  {
    name: "Dengue Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/Dengue Test",
  },
  {
    name: "Pancreatitis Test",
    icon: "/searchTestAndPackages/Disease of Pancreas.svg",
    link: "/search-test/Pancreatitis Test",
  },
  {
    name: "PCOS Test",
    icon: "/searchTestAndPackages/Disease of Reproductive System.svg",
    link: "/search-test/PCOS Test",
  },
  {
    name: "Immunity Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/Immunity Test",
  },
  {
    name: "STD Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    link: "/search-test/STD Test",
  },
];

export const testsInConditions = [
  {
    title: "Pregnancy Checkup",
    icon: "/searchTestAndPackages/Abortions.svg",
    tests: [
      "Complete Blood Count",
      "Thyroid Profile Total",
      "HbA1c",
      "Abnormal Haemoglobin Studies",
      "Blood Group Profile ABO & Rh Typing",
      "Urine Routine Microscope",
      "Blood Glucose Fasting",
      "Hepatitis B Virus (HBV) HbsAg Screening",
      "HIV 1 & 2 Antibodies",
      "Rubella Virus IgG",
      "Anti HCV",
      "Rubella Virus IgM",
      "RPR",
    ],
  },
  {
    title: "Diabetes Test",
    icon: "/searchTestAndPackages/Diabetes.svg",

    tests: [
      "Lipid Profile",
      "LFT",
      "KFT",
      "HbA1c",
      "Urine Routine & Microscopy",
      "Blood Glucose Fasting",
      "Blood Glucose Postprandial",
      "Blood Glucose Random",
    ],
  },
  {
    title: "HIV Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    tests: [
      "Lipid Profile",
      "LFT",
      "Complete Hemogram",
      "KFT",
      "Thyroid Profile Total",
      "Blood Glucose Fasting",
      "HIV 1 & 2 Antibodies",
    ],
  },
  {
    title: "Arthritis Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    tests: [
      "Complete Hemogram",
      "Uric Acid",
      "Calcium",
      "RA Factor",
      "CRP",
      "Vitamin D3",
    ],
  },
  {
    title: "Kidney Function Test",
    icon: "/searchTestAndPackages/Disorders of Kidney.svg",
    tests: [
      "Blood Urea Nitrogen (BUN)",
      "Calcium Total",
      "Chlorides",
      "Creatinine",
      "Phosphorus Inorganic",
      "Sodium",
      "Urea",
      "Uric Acid",
      "BUN/Creatinine Ratio",
      "Urine/Creatinine Routine",
    ],
  },
  {
    title: "Liver Function Test",
    icon: "/searchTestAndPackages/Disease of Liver.svg",
    tests: [
      "Albumin",
      "Alkaline Phosphatase",
      "Bilirubin Direct",
      "Bilirubin Total",
      "GGTP (Gamma GT)",
      "Proteins",
      "SGOT/AST",
      "SGOT/ALT",
      "Bilirubin Indirect",
      "Globulin",
      "A/G Ratio",
      "SGOT/SGPT Ratio",
    ],
  },
  {
    title: "Stool Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    tests: [
      "Color-Stool",
      "Consistency-Stool",
      "Mucus-Stool",
      "Blood-Stool",
      "Plus Cells-Stool",
      "RBC-Stool",
      "Cysts-Stool",
      "Parasites-Stool",
      "OVA-Stool",
      "Others-Stool",
    ],
  },
  {
    title: "Thyroid Test",

    icon: "/searchTestAndPackages/Abortions.svg",
    tests: ["T3", "T4", "TSH"],
  },
  {
    title: "CBC Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    tests: [
      "Absolute Basophils Count",
      "Absolute Eosinophils Count",
      "Absolute Lymphocyte Count",
      "Absolute Monocyte Count",
      "Absolute Neutrophils Count",
      "ESR Automated",

      "Haemoglobin Hb",
      "MCH",
      "MCHC",
      "MCV",
      "Mean Platelet Volume MPV",
      "PCV Haematocrit",

      "Platelet Count Thrombocyte Count",
      "WBS Total Count Leucocytes",
      "RDW Red Cell Distribution Width",
      "Neutrophils",
      "Eosinophils",
      "Lymphocytes",

      "Monocytes",
      "Basophils",
      "RDW CV",
      "MENTZER INDEX",
      "Red Blood Cells-Blood",
      "RDWI ",
      "GK Index",
    ],
  },
  {
    title: "Allergy Test",
    icon: "/searchTestAndPackages/Allergy.svg",
    tests: ["Complete Hemogram", "IgE Total Antibody"],
  },
  {
    title: "Urine Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    tests: ["Urine Routine", "Urine Microscopy"],
  },
  {
    title: "Dengue Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    tests: ["Dengue NS1 Antigen", "Dengue IgG & IgM Antibody"],
  },
  {
    title: "Pancreatitis Test",
    icon: "/searchTestAndPackages/Disease of Pancreas.svg",
    tests: ["LFT", "Complete Hemogram"],
  },
  {
    title: "PCOS Test",
    icon: "/searchTestAndPackages/Disease of Reproductive System.svg",
    tests: [
      "Complete Hemogram",
      "FSH",
      "Insulin Fasting",
      "LH",
      "Prolactin",
      "Testosterone Total",
      "TSH",
    ],
  },
  {
    title: "Immunity Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    tests: [
      "Lipid Profile",
      "LFT",
      "Complete Hemogram",
      "Iron Studies",
      "KFT",
      "CRP",
      "Vitamin D Total",
    ],
  },
  {
    title: "STD Test",
    icon: "/searchTestAndPackages/Abortions.svg",
    tests: [
      "Hepatitis B Virus (HBV) HbsAg Screening",
      "Anti HCV",
      "RPR",
      "HIV 1 & 2 Antibodies",
    ],
  },
];
