export const Tests = [
  {
    title: "Complete Blood Count",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "300",
    type: "test",
  },
  {
    title: "HBA1C",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "550",
    type: "test",
    condition: "Diabetes",
  },
  {
    title: "Malaria Parasite MP",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "LFT",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "650",
    type: "test",
    condition: "Diabetes HIV",
  },
  {
    title: "KFT",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "700",
    type: "test",
    condition: "Diabetes HIV",
  },
  {
    title: "Lipid Profile",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "550",
    type: "test",
    condition: "Diabetes HIV",
  },
  {
    title: "Amylase",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "Lipase",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "CRP",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
    condition: "Arthritis",
  },
  {
    title: "RA Factor",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
    condition: "Arthritis",
  },
  {
    title: "HIV",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "HCV",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "800",
    type: "test",
  },
  {
    title: "HbSAg",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "350",
    type: "test",
  },
  {
    title: "VDRL",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "200",
    type: "test",
  },
  {
    title: "Typhidot Test",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "Dengue",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1200",
    type: "test",
  },
  {
    title: "Sugar Test",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "60",
    type: "test",
  },
  {
    title: "Urine Examination",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "150",
    type: "test",
  },
  {
    title: "Blood Group",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "150",
    type: "test",
  },
  {
    title: "PT/INR",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "APTT",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "300",
    type: "test",
  },
  {
    title: "ESR",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "100",
    type: "test",
  },
  {
    title: "Peripheral Smear P/S (GBS)",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "350",
    type: "test",
  },
  {
    title: "Reticulocyte Count",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "Absolute Eosinophilcount (AEC)",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "Bleeding Time",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "100",
    type: "test",
  },
  {
    title: "Clotting Time",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "100",
    type: "test",
  },
  {
    title: "D-Dimer",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1400",
    type: "test",
  },
  {
    title: "Blood Urea Nitrogen",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "150",
    type: "test",
    condition: "Kidney",
  },
  {
    title: "LDH",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "300",
    type: "test",
  },
  {
    title: "CPK-MB",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "700",
    type: "test",
  },
  {
    title: "CPK Nack",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "Aingiotension Converting Ehzyme",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1000",
    type: "test",
  },
  {
    title: "Free Thyroid Profile",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "750",
    type: "test",
  },
  {
    title: "Thyroid  Profile",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "Viral Masker Test",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1650",
    type: "test",
  },
  {
    title: "Serum Prolactin",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "Cuteimizing Hormone",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "Beta HCG",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "700",
    type: "test",
  },
  {
    title: "Ferritin",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "800",
    type: "test",
  },
  {
    title: "IgE Level",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "700",
    type: "test",
    condition: "Allergy",
  },
  {
    title: "Total PSA ",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "700",
    type: "test",
  },
  {
    title: "Vitamin B12",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1200",
    type: "test",
  },
  {
    title: "Vitamin D3",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1450",
    type: "test",
  },
  {
    title: "CA 125",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1200",
    type: "test",
  },
  {
    title: "Widal Test",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "200",
    type: "test",
  },
  {
    title: "Scrub Tythus Test",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "900",
    type: "test",
  },
  {
    title: "Direct Coombs Test",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "800",
    type: "test",
  },
  {
    title: "Malaria Antigen (MA)",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "200",
    type: "test",
  },
  {
    title: "Sttol Occult Blood",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "Sputum AFB Stain",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "Semen Analysis",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "Urine C/S",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "Gram Stain Pleural Fluid",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "Stool Analysis",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "Indirect Coombs Test",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "800",
    type: "test",
  },
  {
    title: "Magnesium",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "300",
    type: "test",
  },
  {
    title: "Phosphorus",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "Follicle Stimulating Hormone (FSH)",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "550",
    type: "test",
  },
];

// {
//   title: "Pregnancy Check Up",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Diabetes Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "HIV Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Arthritis Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Kidney Function Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Liver Function Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Stool Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Thyroid Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "CBC Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Allergy Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Urine Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Dengue Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Pancreatitis Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "PCOS Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Immunity Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "STD Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
