export const Tests = [
  {
    title: "Complete Blood Count",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "300",
    type: "test",
  },
  {
    title: "HBA1C",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "550",
    type: "test",
  },
  {
    title: "Malaria Parasite MP",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "LFT",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "650",
    type: "test",
  },
  {
    title: "KFT",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "700",
    type: "test",
  },
  {
    title: "Lipid Profile",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "550",
    type: "test",
  },
  {
    title: "Amylase",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "Lipase",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "CRP",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "RA Factor",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "HIV",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "500",
    type: "test",
  },
  {
    title: "HCV",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "800",
    type: "test",
  },
  {
    title: "HbSAg",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "350",
    type: "test",
  },
  {
    title: "VDRL",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "200",
    type: "test",
  },
  {
    title: "Typhidot Test",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "Dengue",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1200",
    type: "test",
  },
  {
    title: "Sugar Test",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "60",
    type: "test",
  },
  {
    title: "Urine Examination",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "150",
    type: "test",
  },
  {
    title: "Blood Group",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "150",
    type: "test",
  },
  {
    title: "PT/INR",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "APTT",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "300",
    type: "test",
  },
  {
    title: "ESR",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "100",
    type: "test",
  },
  {
    title: "Peripheral Smear P/S (GBS)",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "350",
    type: "test",
  },
  {
    title: "Reticulocyte Count",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "Absolute Eosinophilcount (AEC)",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "250",
    type: "test",
  },
  {
    title: "Bleeding Time",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "100",
    type: "test",
  },
  {
    title: "Clotting Time",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "100",
    type: "test",
  },
  {
    title: "D-Dimer",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1400",
    type: "test",
  },
  {
    title: "Blood Urea Nitrogen",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "150",
    type: "test",
  },
  {
    title: "LDH",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "300",
    type: "test",
  },
  {
    title: "CPK-MB",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "700",
    type: "test",
  },
  {
    title: "CPK Nack",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "450",
    type: "test",
  },
  {
    title: "Aingiotension Converting Ehzyme",
    time: "Daily, 2 HRS",
    specimen: "SERUM",
    price: "1000",
    type: "test",
  },
];

// {
//   title: "Pregnancy Check Up",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Diabetes Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "HIV Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Arthritis Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Kidney Function Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Liver Function Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Stool Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Thyroid Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "CBC Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Allergy Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Urine Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Dengue Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Pancreatitis Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "PCOS Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "Immunity Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
// {
//   title: "STD Test",
//   time: "Daily, 2 HRS",
//   specimen: "SERUM",
//   price: "799",
//   type: "test",
// },
