export const healthPackages = [
  {
    id: 1,
    title: "Advanced Arthritis Panel",
    numberOfTests: 7,
    tests: ["CBC", "Uric Acid", "Calcium", "RA Factor..."],
    price: 3750,
    offerPrice: 1900,
  },
  {
    id: 2,
    title: "Basic Arthritis Panel",
    numberOfTests: 5,
    tests: ["CBC", "Uric Acid", "Calcium", "RA Factor..."],
    price: 1690,
    offerPrice: 800,
  },
  {
    id: 3,
    title: "Basic Fever Panel",
    numberOfTests: 5,
    tests: ["CBC + ESR", "MP", "Widal..."],
    price: 1190,
    offerPrice: 666,
  },
  {
    id: 4,
    title: "Advanced Basic Fever Panel",
    numberOfTests: 7,
    tests: ["CBC + ESR", "MP", "Widal", "Urinal R/M..."],
    price: 2560,
    offerPrice: 1500,
  },
  {
    id: 5,
    title: "Advanced Basic Fever Panel",
    numberOfTests: 6,
    tests: ["CBC", "TFT ", "LH ", "FSH..."],
    price: 2500,
    offerPrice: 1200,
  },
  {
    id: 6,
    title: "Diabetes Care Packages",
    numberOfTests: 3,
    tests: ["FBS", "PPBS", "HbA1C..."],
    price: 670,
    offerPrice: 350,
  },
  {
    id: 7,
    title: "Basic Diabetes Care Packages",
    numberOfTests: 6,
    tests: ["FBS", "PPBS", "HbA1C", "Lipid Profile..."],
    price: 1520,
    offerPrice: 888,
  },
  {
    id: 8,
    title: "Advanced Diabetes Care Packages",
    numberOfTests: 7,
    tests: ["FBS", "PPBS", "HbA1C", "Lipid Profile..."],
    price: 4470,
    offerPrice: 2700,
  },
];
