import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Header from "@/components/header";
import Navbar from "@/components/navbar";
import Carousel from "@/components/carousel";
import Feature from "@/components/feature";
import HealthScans from "@/components/healthScans";
import HealthPackages from "@/components/healthPackages";
import Footer from "@/components/footer";
import WhyAarna from "@/components/whyAarna";
import Call from "@/components/call";
import SearchTestPackages from "@/components/searchTestPackages";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ setSidebar, ref3 }) {
  return (
    <div className="">
      <Head>
        <title>Aarna Diagnostic Centre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel />
      <Feature setSidebar={setSidebar} ref3={ref3} />
      <HealthScans />
      <HealthPackages />
      <SearchTestPackages />
      <Call />
      <WhyAarna />
      {/* <h1 className="text-3xl font-bold underline">Hello world!</h1> */}
    </div>
  );
}
