import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Header from "@/components/layout/header";
import Navbar from "@/components/layout/navbar";
import Carousel from "@/components/carousel";
import Feature from "@/components/feature";
import HealthScans from "@/components/healthScans";
import HealthPackages from "@/components/healthPackages";
import Footer from "@/components/layout/footer";
import WhyAarna from "@/components/whyAarna";
import Call from "@/components/call";
import SearchTestAndPackages from "@/components/SearchTestAndPackages";
import Carousel2 from "@/components/carousel2";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ setSidebar, ref3 }) {
  const banners = [
    {
      title: "health panel",
      img: "/banners/BANNERS1.jpg",
    },
    {
      title: "complete health panel",
      img: "/banners/BANNERS3.jpg",
    },
  ];

  const labKiPhotos = [
    {
      title: "lab ki photo 2",
      img: "/banners/IMG_3548.jpg",
    },
    // {
    //   title: "lab ki photo",
    //   img: "/banners/IMG_1309.jpg",
    // },
    // {
    //   title: "lab ki photo 3",
    //   img: "/banners/IMG_1352.jpg",
    // },
    {
      title: "lab ki photo 4",
      img: "/banners/IMG_3559.jpg",
    },
    {
      title: "lab ki photo 5",
      img: "/banners/IMG_3555.jpg",
    },
    // {
    //   title: "lab ki photo 6",
    //   img: "/banners/IMG_1358.jpg",
    // },
    // {
    //   title: "lab ki photo 7",
    //   img: "/banners/IMG_1400.jpg",
    // },
  ];

  return (
    <div className="">
      <Head>
        <title>Aarna Diagnostic Centre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel data={banners} />

      <Feature setSidebar={setSidebar} ref3={ref3} />
      <Carousel2 data={labKiPhotos} />
      <HealthScans />
      <HealthPackages />
      <SearchTestAndPackages />
      <Call />
      <WhyAarna />
      {/* <h1 className="text-3xl font-bold underline">Hello world!</h1> */}
    </div>
  );
}
